//USER
export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const SIGNUP = 'SIGNUP';
export const SENDOTP = 'SENDOTP';
export const VERIFYOTP = 'VERIFYOTP';
export const CHANGEPASSWORD = 'CHANGEPASSWORD';
export const USER = 'USER';
export const NOTIFICATIONSLIST = 'NOTIFICATIONSLIST';

//Bank
export const BANKACCOUNT = 'BANKACCOUNT';
//Address
export const COUNTRIES = 'COUNTRIES';
export const SAVEADDRESS = 'SAVEADDRESS';
export const EDITADDRESS = 'EDITADDRESS';
//Product
export const ADDPRODUCT = 'ADDPRODUCT';
export const USERALLPRODUCT = 'USERALLPRODUCT';
export const DELETEPRODUCT = 'DELETEPRODUCT';
export const EDITPRODUCT = 'EDITPRODUCT';
export const USERSTOREPRODUCTS = 'USERSTOREPRODUCTS';

//Loader
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
//image
export const IMAGEUPLOAD = 'IMAGEUPLOAD';
// user product
export const USERPRODUCT = 'USERPRODUCT';
// categories
export const GETALLCATEGORIES = 'GETALLCATEGORIES';
export const USERLIKEPRODUCT = 'USERLIKEPRODUCT';
export const GETRECENTPRODUCT = 'GETRECENTPRODUCT';
export const GETHOTCATEGORIES = 'GETHOTCATEGORIES';
export const GETPRODUCTSBYCATEGORIES = 'GETPRODUCTSBYCATEGORIES';
//Help Center
export const ADDHELPQUERY = 'ADDHELPQUERY';
//Likes
export const LIKES = 'LIKES';
//Cart
export const ADDTOCART = 'ADDTOCART';
export const GETCARTPRODUCTS = 'GETCARTPRODUCTS';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const REMOVEALLFROMCART = 'REMOVEALLFROMCART';
export const SEARCHEDPRODUCT = 'SEARCHEDPRODUCT';
export const SAVEDSEARCHED = 'SAVEDSEARCHED';
export const GETUSERINFO = 'GETUSERINFO';
export const GETBUYERINPROGRESS = 'GETBUYERINPROGRESS';
export const GETBUYERCOMPLETED = 'GETBUYERCOMPLETED';
export const GETSELLERINPROGRESS = 'GETSELLERINPROGRESS';
export const SETEMPTYCART = 'SETEMPTYCART';
export const GETSELLERCOMPLETED = 'GETSELLERCOMPLETED';
export const SIMILERPRODUCTS = 'SIMILERPRODUCTS';
export const NOTIFICATIONSETTINGINFO = 'NOTIFICATIONSETTINGINFO';
export const GETORDERSTATUS = 'GETORDERSTATUS';
export const GETHOSTELS = 'GETHOSTELS';
export const ADDROOMS = 'ADDROOMS';
export const HOSTELROOMS = 'HOSTELROOMS';
export const GETSHOPS = 'GETSHOPS';
export const GETREVIEWS = 'GETREVIEWS';
